
server:
  port: 8081

app:
  client_id: 3dd0e341-d18b-42d8-b981-a701dc3f62c1
  secret_id: 692611d1-6a0c-4f08-9099-6b0496dd9400
  signing_key_jwt: 692611d1-6a0c-4f08-9099-6b0496dd9400

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/marketplace?useSSL=false
    username: root
    password: admin

  jpa:
    hibernate.ddl-auto: none
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
