
server:
  port: 8081

app:
  client_id: admin
  secret_id: 12345
  signing_key_jwt: api-security-oauth2

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/marketplace?useSSL=false
    username: root
    password: admin

  jpa:
    hibernate.ddl-auto: none
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
